robot:
    odom_topic: "odom" 

local_planner:
    goal_tolerance: 0.05 
    trajectory_lookahed_count: 15 

    wait_full_step: True
    visualize_trajs: True
    visualize_state: True

mppic:
    noise_repeat_factor: 1
    batch_size: 300
    time_steps: 40
    model_path: "$(find rosbot_controller)/nets/new_model_dynamic_batch.onnx"
    mppi_freq: 10
    iter_count: 2
    v_std: 0.10
    w_std: 0.25
    limit_v: 0.5
    limit_w:  1.0
    desired_v: 0.3
    traj_lookahead: 1.7


# x, y, Radius
obstacles: [ [1.0, 0.75,  0.3], 
             [2.5, 0.55,  0.3],
            ]
