robot:
    odom_topic: "odom" 

local_planner:
    goal_tolerance: 0.2 
    traj_lookahead: 10

    wait_full_step: True 
    visualize_trajs: True

mppic:
    batch_size: 300 
    time_steps: 40
    model_path: "$(find rosbot_controller)/nets/new_model_dynamic_batch.onnx"
    mppi_freq: 10
    iter_count: 4
    goals_interval: 0.1
    v_std: 0.10
    w_std: 0.10
    limit_v: 0.5
    limit_w:  0.7
    desired_v: 0.3
    traj_lookahead: 15
