robot:
    odom_topic: "odom" 

local_planner:
    goal_tolerance: 0.05 
    trajectory_lookahed_count: 4

    wait_full_step: False
    visualize_trajs: True

mppic:
    noise_repeat_factor: 2
    batch_size: 300
    time_steps: 40
    model_path: "$(find rosbot_controller)/nets/new_model_dynamic_batch.onnx"
    mppi_freq: 10
    iter_count: 3
    v_std: 0.10
    w_std: 0.25
    limit_v: 0.5
    limit_w:  1.0
    desired_v: 0.3
    traj_lookahead: 1.5
