robot:
    map_frame: "odom" 
    base_frame: "base_link"

local_planner:
    goal_tolerance: 0.2 
    controller_freq: 90
    traj_lookahead: 3 

mppic:
    batch_size: 100 
    time_steps: 50
    model_path: "$(find rosbot_controller)/nets/model_batch_100.onnx"
    mppi_freq: 30
    iter_count: 1
    goals_interval: 0.1
    v_std: 0.2
    w_std: 0.3
    limit_v: 0.5
    limit_w:  0.7
    desired_v: 0.4
    traj_lookahead: 6 
