mppic:
    use_nn_model: True
    model_path: "$(find rosbot_controller)/nets/new_model_dynamic_batch.onnx"

obstacles: [              
              [1, 0,  0.3],
              [2.5, 0.55,  0.3],
              [4, 0.3, 0.3]
           ]

robot:
    odom_topic: "odom" 

goal_handler:
    goal_tolerance: 0.05 

local_planner:
    wait_full_step: False
    visualize: False

optimizer:
    iter_count: 2
    traj_lookahead: 1.5

generator:
    batch_size: 300
    time_steps: 40
    model_dt: 0.1
    v_std: 0.10
    w_std: 0.10
    limit_v: 0.5
    limit_w:  1.3
